//
//  FoodItem.swift
//  BiteLedger
//
//  Created by Craig Faist on 2/16/26.
//

import SwiftData
import Foundation

// MARK: - NutritionMode

public enum NutritionMode: String, Codable {
    /// Nutrition values stored per 100g. Used for packaged foods, USDA whole foods.
    /// ServingSizes must have gramWeight to calculate correctly.
    case per100g

    /// Nutrition values stored per 1 default serving. Used for manual entry,
    /// recipes, FatSecret no-gram items, and LoseIt imports.
    case perServing
}

// MARK: - MealType

public enum MealType: String, Codable, CaseIterable, Identifiable {
    case breakfast = "Breakfast"
    case lunch     = "Lunch"
    case dinner    = "Dinner"
    case snack     = "Snack"

    public var id: String { rawValue }

    public var icon: String {
        switch self {
        case .breakfast: return "sunrise"
        case .lunch:     return "sun.max"
        case .dinner:    return "moon"
        case .snack:     return "leaf"
        }
    }
}

// MARK: - FoodItem

@Model
public final class FoodItem {

    // MARK: Identity
    // CloudKit requires all stored properties to be optional or have default values.
    public var id: UUID = UUID()
    public var name: String = ""
    public var brand: String?
    public var barcode: String?
    public var source: String = ""
    public var dateAdded: Date = Date()

    // MARK: Nutrition Mode
    public var nutritionMode: NutritionMode = NutritionMode.per100g

    // MARK: Nutrition Values
    public var calories: Double = 0
    public var protein: Double = 0
    public var carbs: Double = 0
    public var fat: Double = 0

    // Optional macros
    public var fiber: Double?
    public var sugar: Double?
    public var saturatedFat: Double?
    public var transFat: Double?
    public var polyunsaturatedFat: Double?
    public var monounsaturatedFat: Double?

    // Optional minerals (mg)
    public var sodium: Double?
    public var cholesterol: Double?
    public var potassium: Double?
    public var calcium: Double?
    public var iron: Double?
    public var magnesium: Double?
    public var zinc: Double?

    // Optional vitamins
    public var vitaminA: Double?
    public var vitaminC: Double?
    public var vitaminD: Double?
    public var vitaminE: Double?
    public var vitaminK: Double?
    public var vitaminB6: Double?
    public var vitaminB12: Double?
    public var folate: Double?
    public var choline: Double?

    // Optional other
    public var caffeine: Double?

    // MARK: Canonical Reference

    /// Links this food to a CanonicalFood entry for density-based gram estimates.
    /// Set at import time when a match is found. nil for foods with no canonical match.
    public var canonicalFoodID: UUID? = nil

    /// Links this food to the FallbackSource record that provided micronutrient enrichment.
    /// Set during LoseIt enrichment import. nil for foods not enriched from an external source.
    public var fallbackSourceID: UUID? = nil

    // MARK: Relationships
    @Relationship(deleteRule: .cascade) public var servingSizes: [ServingSize] = []
    @Relationship(deleteRule: .nullify) public var foodLogs: [FoodLog] = []
    // NOTE: FoodHistoryEntry has a unidirectional food→FoodItem relationship (no back-reference here).
    // Keeping FoodItem free of a historyEntries relationship avoids SwiftData "Duplicate version
    // checksums detected" — SwiftData follows relationship edges when fingerprinting each schema
    // version, so a back-reference on FoodItem would make V1 and V2 produce identical checksums.
    // Orphaned FoodHistoryEntry records (food set to nil after FoodItem deletion) are filtered out
    // at display time via compactMap { $0.food }.

    /// Set when this FoodItem was generated by a Recipe. nil for all non-recipe foods.
    /// Recipe-sourced FoodItems are excluded from MyFoodsManagementView — manage them via MyRecipesView.
    public var recipe: Recipe?

    // MARK: Init
    public init(
        id: UUID = UUID(),
        name: String,
        brand: String? = nil,
        barcode: String? = nil,
        source: String,
        dateAdded: Date = Date(),
        nutritionMode: NutritionMode,
        canonicalFoodID: UUID? = nil,
        calories: Double,
        protein: Double,
        carbs: Double,
        fat: Double,
        fiber: Double? = nil,
        sugar: Double? = nil,
        saturatedFat: Double? = nil,
        transFat: Double? = nil,
        polyunsaturatedFat: Double? = nil,
        monounsaturatedFat: Double? = nil,
        sodium: Double? = nil,
        cholesterol: Double? = nil,
        potassium: Double? = nil,
        calcium: Double? = nil,
        iron: Double? = nil,
        magnesium: Double? = nil,
        zinc: Double? = nil,
        vitaminA: Double? = nil,
        vitaminC: Double? = nil,
        vitaminD: Double? = nil,
        vitaminE: Double? = nil,
        vitaminK: Double? = nil,
        vitaminB6: Double? = nil,
        vitaminB12: Double? = nil,
        folate: Double? = nil,
        choline: Double? = nil,
        caffeine: Double? = nil
    ) {
        self.id = id
        self.name = name
        self.brand = brand
        self.barcode = barcode
        self.source = source
        self.dateAdded = dateAdded
        self.nutritionMode = nutritionMode
        self.canonicalFoodID = canonicalFoodID
        self.calories = calories
        self.protein = protein
        self.carbs = carbs
        self.fat = fat
        self.fiber = fiber
        self.sugar = sugar
        self.saturatedFat = saturatedFat
        self.transFat = transFat
        self.polyunsaturatedFat = polyunsaturatedFat
        self.monounsaturatedFat = monounsaturatedFat
        self.sodium = sodium
        self.cholesterol = cholesterol
        self.potassium = potassium
        self.calcium = calcium
        self.iron = iron
        self.magnesium = magnesium
        self.zinc = zinc
        self.vitaminA = vitaminA
        self.vitaminC = vitaminC
        self.vitaminD = vitaminD
        self.vitaminE = vitaminE
        self.vitaminK = vitaminK
        self.vitaminB6 = vitaminB6
        self.vitaminB12 = vitaminB12
        self.folate = folate
        self.choline = choline
        self.caffeine = caffeine
    }

    // MARK: Normalization

    /// Converts all stored nutrition values from per-serving to per-100g in place.
    /// Call this immediately after creating a FoodItem with per-serving inputs.
    ///
    /// - Parameter gramWeightPerServing: The gram weight of 1 default serving.
    ///   Pass `nil` when unknown — uses 100g/serving nominal (values unchanged, factor = 1.0).
    ///
    /// After this call `nutritionMode` is `.per100g` and all fields store per-100g values.
    /// The companion `ServingSize.gramWeight` must be set to `gramWeightPerServing ?? 100`
    /// at the call site (this method does not own servings).
    public func normalizeToPerHundredGrams(gramWeightPerServing: Double?) {
        let effectiveGrams = gramWeightPerServing ?? 100.0
        guard effectiveGrams > 0 else { return }
        let factor = 100.0 / effectiveGrams
        calories           *= factor
        protein            *= factor
        carbs              *= factor
        fat                *= factor
        fiber               = fiber.map            { $0 * factor }
        sugar               = sugar.map            { $0 * factor }
        saturatedFat        = saturatedFat.map     { $0 * factor }
        transFat            = transFat.map         { $0 * factor }
        polyunsaturatedFat  = polyunsaturatedFat.map { $0 * factor }
        monounsaturatedFat  = monounsaturatedFat.map { $0 * factor }
        sodium              = sodium.map           { $0 * factor }
        cholesterol         = cholesterol.map      { $0 * factor }
        potassium           = potassium.map        { $0 * factor }
        calcium             = calcium.map          { $0 * factor }
        iron                = iron.map             { $0 * factor }
        magnesium           = magnesium.map        { $0 * factor }
        zinc                = zinc.map             { $0 * factor }
        vitaminA            = vitaminA.map         { $0 * factor }
        vitaminC            = vitaminC.map         { $0 * factor }
        vitaminD            = vitaminD.map         { $0 * factor }
        vitaminE            = vitaminE.map         { $0 * factor }
        vitaminK            = vitaminK.map         { $0 * factor }
        vitaminB6           = vitaminB6.map        { $0 * factor }
        vitaminB12          = vitaminB12.map       { $0 * factor }
        folate              = folate.map           { $0 * factor }
        choline             = choline.map          { $0 * factor }
        caffeine            = caffeine.map         { $0 * factor }
        nutritionMode       = .per100g
    }

    // MARK: Computed Helpers

    /// The default serving size for display in pickers and search results.
    public var defaultServing: ServingSize? {
        servingSizes.first(where: { $0.isDefault })
            ?? servingSizes.min(by: { $0.sortOrder < $1.sortOrder })
    }

    /// Display name including brand if available.
    public var displayName: String {
        if let brand, !brand.isEmpty {
            return "\(name) · \(brand)"
        }
        return name
    }
}
